server:
  port: 8080
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: postgresql://postgres:oQeneb1ly2w8sTAjE0OC@containers-us-west-94.railway.app:7158/railway
    username: postgres
    password: oQeneb1ly2w8sTAjE0OC
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
  liquibase:
    change-log: static/db/changelog/changelog-master.yml